services:
  db-pets:
    image: mysql:latest
    container_name: pets
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pets
      MYSQL_USER: pets
      MYSQL_PASSWORD: pets_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Asegúrate de que el volumen esté definido

volumes:
  db_data: {}  # Define el volumen aquí